### ISSUE TITLE
npm package installation bug

### ISSUE THREAD

**Issue by Nisfan** [denimar/deni-react-treeview#4]
I am getting following error message after install and run with

visual studio code in windows 10
npm install deni-react-treeview --save

I tried by running the command `npm rebuild node-sass --force` still no success

`Error: Module build failed: Error: Missing binding /home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/node-sass/vendor/linux-x64-57/binding.node
Node Sass could not find a binding for your current environment: Linux 64-bit with Node.js 8.x

Found bindings for the following environments:
  - Linux 64-bit with Node.js 4.x

This usually happens because your environment has changed since running `npm install`.
Run `npm rebuild node-sass --force` to build the binding for your current environment.
    at module.exports (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/node-sass/lib/binding.js:15:13)
    at Object.<anonymous> (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at loadLoader (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/webpack/lib/NormalModule.js:182:3)
    at NormalModule.build (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/webpack/lib/NormalModule.js:275:15)
    at Compilation.buildModule (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/webpack/lib/Compilation.js:151:10)
    at factoryCallback (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/webpack/lib/Compilation.js:344:12)
    at factory (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/webpack/lib/NormalModuleFactory.js:241:5)
    at applyPluginsAsyncWaterfall (/home/denimar/Desktop/Denimar/personal/apps/deni-react-treeview/node_modules/webpack/lib/NormalModuleFactory.js:94:13)`

**Comment by denimar** [comment]
Hi Nisfan, tks for this issue!
Sorry for this late answer....
Could you try to do it again, because I think it doesn't happen anymore?
examples: https://denimar.github.io/deni-react-treeview/examples

**Comment by Nisfan** [comment]
installation

![image](https://user-images.githubusercontent.com/22009890/36520279-27040b3a-17b6-11e8-85a5-a7ce28d3c428.png)

after run

![image](https://user-images.githubusercontent.com/22009890/36520308-556add5a-17b6-11e8-8f0e-ce8899fd8dbc.png)

**Comment by denimar** [comment]
Thank you again Nisfan!
As soon as I can I will fix it.
If you want to fix this problem, be free. Send me a pull request after that

**Comment by FrozenKiwi** [comment]
I'm having the same issue.

Tried downloading the repo as zip and installing from there and same result

**Comment by denimar** [comment]
I am closing this issue because I thing this error doesn't happen anymore. I could see that by installing the same environment mentioned here and what I saw was everything running perfectly.
I anybody face this problem, I open this issue again.
